"""Добавлена колонка subjects=[]

Revision ID: 0938e640bfb1
Revises: 88b55ec276c5
Create Date: 2026-07-11 16:14:15.855258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0938e640bfb1'
down_revision = '88b55ec276c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
