"""pomodoro in users

Revision ID: 2ad0e2dc9dbc
Revises: dbce133bbc96
Create Date: 2026-07-12 19:48:06.927372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad0e2dc9dbc'
down_revision = 'dbce133bbc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_work_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cycle_break_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('auto_start', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('auto_start')
        batch_op.drop_column('cycle_break_time')
        batch_op.drop_column('cycle_work_time')

    # ### end Alembic commands ###
