"""Добавлена колонка subjects для User

Revision ID: 88b55ec276c5
Revises: f81f30c1d1e6
Create Date: 2026-07-11 15:56:40.889347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b55ec276c5'
down_revision = 'f81f30c1d1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subjects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
