"""user subject unique

Revision ID: b2930f85b133
Revises: 3b7f22e3e685
Create Date: 2026-07-12 13:38:17.931988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2930f85b133'
down_revision = '3b7f22e3e685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_name'), type_='unique')
        batch_op.create_unique_constraint('uq_user_subject', ['user_id', 'name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_subject', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_subject_name'), ['name'])

    # ### end Alembic commands ###
