"""added goal

Revision ID: dbce133bbc96
Revises: b2930f85b133
Create Date: 2026-07-12 18:31:47.506378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbce133bbc96'
down_revision = 'b2930f85b133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('goal_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.INTEGER(), nullable=True))
        batch_op.drop_column('goal_date')
        batch_op.drop_column('goal_name')

    # ### end Alembic commands ###
