"""Добавлена колонка subjects для User

Revision ID: f81f30c1d1e6
Revises: 
Create Date: 2026-07-11 15:32:43.860815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f81f30c1d1e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.drop_table('olimpiads')
    op.drop_table('focus_sessions')
    op.drop_table('topics')
    op.drop_table('subject')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subjects')

    op.create_table('subject',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('focus_sessions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('olimpiads',
    sa.Column('id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('subjects', sqlite.JSON(), nullable=True),
    sa.Column('dates', sqlite.JSON(), nullable=True),
    sa.Column('url', sa.VARCHAR(length=100), nullable=True),
    sa.Column('classes', sa.VARCHAR(length=20), nullable=True),
    sa.Column('level_perechnya', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
