"""ai challenges

Revision ID: f88d1a683cfa
Revises: 2ad0e2dc9dbc
Create Date: 2026-07-17 11:35:00.517320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f88d1a683cfa'
down_revision = '2ad0e2dc9dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_text', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('last_ai_get', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_ai_get')
        batch_op.drop_column('ai_text')

    # ### end Alembic commands ###
